name: clash-pong
version: 0.1.0
category: hardware, game
license: MIT

extra-source-files:
  - README.md

custom-setup:
  dependencies:
    - base
    - Cabal
    - clashilator
    
dependencies:
  - base
  - clash-prelude
  - clash-lib
  - clash-ghc
  - retroclash-lib
  
  - clash-shake ^>= 0.3.0

  - lens
  - mtl

# Anything that Clash uses by default should go here
default-extensions:
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric
  - DeriveLift
  - DerivingStrategies
  - ExplicitForAll
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - KindSignatures
  - MagicHash
  - MonoLocalBinds
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - NoStarIsType
  - NoStrictData
  - NoStrict
  - QuasiQuotes
  - ScopedTypeVariables
  - TemplateHaskellQuotes
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeInType
  - TypeOperators

source-dirs:
  - src

flags:
  sim:
    manual: True
    default: True
  verilator:
    manual: True
    default: False

executables:
  pong:
    main: simulator.hs
    dependencies:
      - retroclash-sim
      - text
      - array
      - monad-loops
    when:
    - condition: "!flag(sim)"
      buildable: false

  pong-clash:
    main: simulator-clash.hs
    dependencies:
      - retroclash-sim
      - text
      - array
      - monad-loops
    when:
    - condition: "!flag(sim)"
      buildable: false

  pong-verilator:
    main: simulator-verilator.hs
    other-modules: []
    dependencies:
      - retroclash-sim
      - monad-loops
    verbatim:
      x-clashilator-top-is: Pong
    when:
    - condition: "!(flag(sim) && flag(verilator))"
      buildable: false
